name: 'PowerTools'
version: '0.3.0-SNAPSHOT'
main: 'org.winlogon.powertools.PowerToolsPlugin'
description: 'Fun utilities for everyone!'
folia-supported: true
api-version: 1.21
permissions:
  powertools.invsee:
    default: op
  powertools.smite:
    default: op
  powertools.hat:
    default: true
  powertools.broadcast:
    default: op
  whitelist.manage:
    default: op
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
