name: 'PowerTools'
version: '0.4.0-SNAPSHOT'
main: 'org.winlogon.powertools.PowerToolsPlugin'
description: 'Fun utilities for everyone!'
folia-supported: true
api-version: 1.21
dependencies:
  server:
    CommandAPI:
      load: BEFORE
      required: true
      join-classpath: true
    ScalaLoader:
      load: BEFORE
      required: true
      join-classpath: true
