name: '${NAME}'
version: '${VERSION}'
main: '${PACKAGE}.PowerToolsPlugin'
loader: '${PACKAGE}.PowerToolsLoader'
description: 'Fun utilities for everyone!'
folia-supported: true
api-version: '${API_VERSION}'
