name: 'PowerTools'
version: '0.2.0-SNAPSHOT'
main: 'org.winlogon.powertools.PowerToolsPlugin'
description: 'Fun utilities for everyone!'
folia-supported: true
api-version: 1.21
permissions:
  powertools.invsee:
    default: op
  powertools.smite:
    default: op
  powertools.hat:
    default: true
  powertools.broadcast:
    default: op
commands:
  invsee:
    description: "See other players' inventories"
    usage: /<command> <player>
    default: op
  broadcast:
    description: "Broadcast a message to all players"
    usage: /<command> <message>
    aliases: [bc]
    default: op
  smite:
    description: "Send your enemies a taste of electricity from the sky!"
    usage: /<command> <player>
    default: op
  hat:
    description: "Put the item you're holding on your head"
    usage: /<command>
    default: true
